import { BUSINESS } from '../../constants/business.js';

export default function PrintReportFooter() {
  return (
    <div className="hidden print:block">
      <div className="my-4 border-t border-dashed border-slate-300" />
      <div className="text-center text-[11px] text-slate-400">
        <p className="font-semibold text-slate-500">{BUSINESS.name}</p>
        <p>{BUSINESS.addressLine}</p>
        <p>{BUSINESS.phone}</p>
        <p className="mt-1">Generated by Inventory &amp; POS System</p>
      </div>
    </div>
  );
}
